# Travis CI configuration
# see https://docs.travis-ci.com/user/languages/python

language: python

arch: arm64

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .

script: python setup.py test

arch: arm64
addons:
  postgresql: "10"

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database unittest'
